import type {
  ApplicationIntegrationType,
  RawApplication,
} from './application.js';
import type { ChannelType, RawChannel, RawThreadMember } from './channel.js';
import type { ISO8601Timestamp, Snowflake } from './common.js';
import type { RawComponent } from './component.js';
import type { RawEmoji } from './emoji.js';
import type {
  InteractionType,
  RawMessageInteraction,
  RawResolvedData,
} from './interaction.js';
import type { RawPoll, RawPollCreateRequest } from './poll.js';
import type { RawSticker, RawStickerItem } from './sticker.js';
import type { RawUser } from './user.js';

/**
 * Message Structure
 * @see https://docs.discord.com/developers/resources/message#message-object-message-structure
 */
export interface RawMessage {
  /** id of the message */
  id: Snowflake;
  /** id of the channel the message was sent in */
  channel_id: Snowflake;
  /** the author of this message (not guaranteed to be a valid user, see below) */
  author: RawUser;
  /** contents of the message */
  content: string;
  /** when this message was sent */
  timestamp: ISO8601Timestamp;
  /** when this message was edited (or null if never) */
  edited_timestamp: ISO8601Timestamp | null;
  /** whether this was a TTS message */
  tts: boolean;
  /** whether this message mentions everyone */
  mention_everyone: boolean;
  /** users specifically mentioned in the message */
  mentions: RawUser[];
  /** roles specifically mentioned in this message */
  mention_roles: Snowflake[];
  /** channels specifically mentioned in this message */
  mention_channels?: RawChannelMention[];
  /** any attached files that are not referenced in embeds or components */
  attachments: RawAttachment[];
  /** any embedded content */
  embeds: RawEmbed[];
  /** reactions to the message */
  reactions?: RawReaction[];
  /** used for validating a message was sent */
  nonce?: number | string;
  /** whether this message is pinned */
  pinned: boolean;
  /** if the message is generated by a webhook, this is the webhook's id */
  webhook_id?: Snowflake;
  /** type of message */
  type: MessageType;
  /** sent with Rich Presence-related chat embeds */
  activity?: RawMessageActivity;
  /** sent with Rich Presence-related chat embeds */
  application?: Partial<RawApplication>;
  /** if the message is an Interaction or application-owned webhook, this is the id of the application */
  application_id?: Snowflake;
  /** message flags combined as a bitfield */
  flags?: number;
  /** data showing the source of a crosspost, channel follow add, pin, or reply message */
  message_reference?: RawMessageReference;
  /** the message associated with the `message_reference`. This is a minimal subset of fields in a message (e.g. `author` is excluded.) */
  message_snapshots?: RawMessageSnapshot[];
  /** the message associated with the message_reference */
  referenced_message?: RawMessage | null;
  /** Sent if the message is sent as a result of an interaction */
  interaction_metadata?: RawMessageInteractionMetadata;
  /** **Deprecated in favor of `interaction_metadata`**; sent if the message is a response to an interaction */
  interaction?: RawMessageInteraction;
  /** the thread that was started from this message, includes thread member object */
  thread?: RawChannel;
  /** sent if the message contains components like buttons, action rows, or other interactive components */
  components?: RawComponent[];
  /** sent if the message contains stickers */
  sticker_items?: RawStickerItem[];
  /** **Deprecated** the stickers sent with the message */
  stickers?: RawSticker[];
  /** A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a thread, it can be used to estimate the relative position of the message in a thread in company with `total_message_sent` on parent thread */
  position?: number;
  /** data of the role subscription purchase or renewal that prompted this ROLE_SUBSCRIPTION_PURCHASE message */
  role_subscription_data?: RawRoleSubscriptionData;
  /** data for users, members, channels, and roles referenced in this message */
  resolved?: RawResolvedData;
  /** A poll! */
  poll?: RawPoll;
  /** the call associated with the message */
  call?: RawMessageCall;
  /** the custom client-side theme shared via the message */
  shared_client_theme?: RawSharedClientTheme;
}

/**
 * Message Types
 * @see https://docs.discord.com/developers/resources/message#message-object-message-types
 */
export const MessageType = {
  Default: 0,
  RecipientAdd: 1,
  RecipientRemove: 2,
  Call: 3,
  ChannelNameChange: 4,
  ChannelIconChange: 5,
  ChannelPinnedMessage: 6,
  UserJoin: 7,
  GuildBoost: 8,
  GuildBoostTier1: 9,
  GuildBoostTier2: 10,
  GuildBoostTier3: 11,
  ChannelFollowAdd: 12,
  GuildDiscoveryDisqualified: 14,
  GuildDiscoveryRequalified: 15,
  GuildDiscoveryGracePeriodInitialWarning: 16,
  GuildDiscoveryGracePeriodFinalWarning: 17,
  ThreadCreated: 18,
  Reply: 19,
  ChatInputCommand: 20,
  ThreadStarterMessage: 21,
  GuildInviteReminder: 22,
  ContextMenuCommand: 23,
  AutoModerationAction: 24,
  RoleSubscriptionPurchase: 25,
  InteractionPremiumUpsell: 26,
  StageStart: 27,
  StageEnd: 28,
  StageSpeaker: 29,
  StageTopic: 31,
  GuildApplicationPremiumSubscription: 32,
  GuildIncidentAlertModeEnabled: 36,
  GuildIncidentAlertModeDisabled: 37,
  GuildIncidentReportRaid: 38,
  GuildIncidentReportFalseAlarm: 39,
  PurchaseNotification: 44,
  PollResult: 46,
} as const;
export type MessageType = (typeof MessageType)[keyof typeof MessageType];

/**
 * Message Activity Structure
 * @see https://docs.discord.com/developers/resources/message#message-object-message-activity-structure
 */
export interface RawMessageActivity {
  /** type of message activity */
  type: MessageActivityType;
  /** party_id from a Rich Presence event */
  party_id?: string;
}

/**
 * Message Activity Types
 * @see https://docs.discord.com/developers/resources/message#message-object-message-activity-types
 */
export const MessageActivityType = {
  Join: 1,
  Spectate: 2,
  Listen: 3,
  JoinRequest: 5,
  StreamRequest: 6,
} as const;
export type MessageActivityType =
  (typeof MessageActivityType)[keyof typeof MessageActivityType];

/**
 * Message Flags
 * @see https://docs.discord.com/developers/resources/message#message-object-message-flags
 */
export const MessageFlags = {
  /** this message has been published to subscribed channels (via Channel Following) */
  Crossposted: 1 << 0,
  /** this message originated from a message in another channel (via Channel Following) */
  IsCrosspost: 1 << 1,
  /** do not include any embeds when serializing this message */
  SuppressEmbeds: 1 << 2,
  /** the source message for this crosspost has been deleted (via Channel Following) */
  SourceMessageDeleted: 1 << 3,
  /** this message came from the urgent message system */
  Urgent: 1 << 4,
  /** this message has an associated thread, with the same id as the message */
  HasThread: 1 << 5,
  /** this message is only visible to the user who invoked the Interaction */
  Ephemeral: 1 << 6,
  /** this message is an Interaction Response and the bot is "thinking" */
  Loading: 1 << 7,
  /** this message failed to mention some roles and add their members to the thread */
  FailedToMentionSomeRolesInThread: 1 << 8,
  /** this message will not trigger push and desktop notifications */
  SuppressNotifications: 1 << 12,
  /** this message is a voice message */
  IsVoiceMessage: 1 << 13,
  /** this message has a snapshot (via Message Forwarding) */
  HasSnapshot: 1 << 14,
  /** allows you to create fully component-driven messages */
  IsComponentsV2: 1 << 15,
} as const;
export type MessageFlags = (typeof MessageFlags)[keyof typeof MessageFlags];

/**
 * Application Command Interaction Metadata Structure
 * @see https://docs.discord.com/developers/resources/message#message-interaction-metadata-object-application-command-interaction-metadata-structure
 */
export interface RawApplicationCommandInteractionMetadata {
  /** ID of the interaction */
  id: Snowflake;
  /** Type of interaction */
  type: typeof InteractionType.ApplicationCommand;
  /** User who triggered the interaction */
  user: RawUser;
  /** IDs for installation context(s) related to an interaction. Details in Authorizing Integration Owners Object */
  authorizing_integration_owners: Partial<
    Record<`${ApplicationIntegrationType}`, Snowflake>
  >;
  /** ID of the original response message, present only on follow-up messages */
  original_response_message_id?: Snowflake;
  /** The user the command was run on, present only on user command interactions */
  target_user?: RawUser;
  /** The ID of the message the command was run on, present only on message command interactions. The original response message will also have `message_reference` and `referenced_message` pointing to this message. */
  target_message_id?: Snowflake;
}

/**
 * Message Component Interaction Metadata Structure
 * @see https://docs.discord.com/developers/resources/message#message-interaction-metadata-object-message-component-interaction-metadata-structure
 */
export interface RawMessageComponentInteractionMetadata {
  /** ID of the interaction */
  id: Snowflake;
  /** Type of interaction */
  type: typeof InteractionType.MessageComponent;
  /** User who triggered the interaction */
  user: RawUser;
  /** IDs for installation context(s) related to an interaction. Details in Authorizing Integration Owners Object */
  authorizing_integration_owners: Partial<
    Record<`${ApplicationIntegrationType}`, Snowflake>
  >;
  /** ID of the original response message, present only on follow-up messages */
  original_response_message_id?: Snowflake;
  /** ID of the message that contained the interactive component */
  interacted_message_id: Snowflake;
}

/**
 * Modal Submit Interaction Metadata Structure
 * @see https://docs.discord.com/developers/resources/message#message-interaction-metadata-object-modal-submit-interaction-metadata-structure
 */
export interface RawModalSubmitInteractionMetadata {
  /** ID of the interaction */
  id: Snowflake;
  /** Type of interaction */
  type: typeof InteractionType.ModalSubmit;
  /** User who triggered the interaction */
  user: RawUser;
  /** IDs for installation context(s) related to an interaction. Details in Authorizing Integration Owners Object */
  authorizing_integration_owners: Partial<
    Record<`${ApplicationIntegrationType}`, Snowflake>
  >;
  /** ID of the original response message, present only on follow-up messages */
  original_response_message_id?: Snowflake;
  /** Metadata for the interaction that was used to open the modal */
  triggering_interaction_metadata:
    | RawApplicationCommandInteractionMetadata
    | RawMessageComponentInteractionMetadata;
}

/**
 * Message Call Object Structure
 * @see https://docs.discord.com/developers/resources/message#message-call-object-message-call-object-structure
 */
export interface RawMessageCall {
  /** array of user object ids that participated in the call */
  participants: Snowflake[];
  /** time when call ended */
  ended_timestamp?: ISO8601Timestamp | null;
}

/**
 * Message Reference Structure
 * @see https://docs.discord.com/developers/resources/message#message-reference-structure
 */
export interface RawMessageReference {
  /** type of reference. */
  type?: MessageReferenceType;
  /** id of the originating message */
  message_id?: Snowflake;
  /** id of the originating message's channel */
  channel_id?: Snowflake;
  /** id of the originating message's guild */
  guild_id?: Snowflake;
  /** when sending, whether to error if the referenced message doesn't exist instead of sending as a normal (non-reply) message, default true */
  fail_if_not_exists?: boolean;
}

/**
 * Message Reference Types
 * @see https://docs.discord.com/developers/resources/message#message-reference-types
 */
export const MessageReferenceType = {
  /** A standard reference used by replies. */
  Default: 0,
  /** Reference used to point to a message at a point in time. */
  Forward: 1,
} as const;
export type MessageReferenceType =
  (typeof MessageReferenceType)[keyof typeof MessageReferenceType];

/**
 * Message Snapshot Structure
 * @see https://docs.discord.com/developers/resources/message#message-snapshot-structure
 */
export interface RawMessageSnapshot {
  /** minimal subset of fields in the forwarded message */
  message: Partial<RawMessage>;
}

/**
 * Reaction Structure
 * @see https://docs.discord.com/developers/resources/message#reaction-object-reaction-structure
 */
export interface RawReaction {
  /** Total number of times this emoji has been used to react (including super reacts) */
  count: number;
  /** Reaction count details object */
  count_details: RawReactionCountDetails;
  /** Whether the current user reacted using this emoji */
  me: boolean;
  /** Whether the current user super-reacted using this emoji */
  me_burst: boolean;
  /** emoji information */
  emoji: Partial<RawEmoji>;
  /** HEX colors used for super reaction */
  burst_colors: string[];
}

/**
 * Reaction Count Details Structure
 * @see https://docs.discord.com/developers/resources/message#reaction-count-details-object-reaction-count-details-structure
 */
export interface RawReactionCountDetails {
  /** Count of super reactions */
  burst: number;
  /** Count of normal reactions */
  normal: number;
}

/**
 * Embed Structure
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-structure
 */
export interface RawEmbed {
  /** title of embed */
  title?: string;
  /** type of embed (always "rich" for webhook embeds) */
  type?: EmbedType;
  /** description of embed */
  description?: string;
  /** url of embed */
  url?: string;
  /** timestamp of embed content */
  timestamp?: ISO8601Timestamp;
  /** color code of the embed */
  color?: number;
  /** footer information */
  footer?: RawEmbedFooter;
  /** image information */
  image?: RawEmbedImage;
  /** thumbnail information */
  thumbnail?: RawEmbedImage;
  /** video information */
  video?: RawEmbedVideo;
  /** provider information */
  provider?: RawEmbedProvider;
  /** author information */
  author?: RawEmbedAuthor;
  /** fields information, max of 25 */
  fields?: RawEmbedField[];
  /** embed flags combined as a bitfield */
  flags?: number;
}

/**
 * Embed Flags
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-flags
 */
export const EmbedFlags = {
  /** this embed is a fallback for a reply to an activity card */
  IsContentInventoryEntry: 1 << 5,
} as const;
export type EmbedFlags = (typeof EmbedFlags)[keyof typeof EmbedFlags];

/**
 * Embed Video Structure
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-video-structure
 */
export interface RawEmbedVideo {
  /** source url of video */
  url?: string;
  /** a proxied url of the video */
  proxy_url?: string;
  /** height of video */
  height?: number;
  /** width of video */
  width?: number;
  /** the video's media type */
  content_type?: string;
  /** thumbhash placeholder of the video */
  placeholder?: string;
  /** version of the placeholder */
  placeholder_version?: number;
  /** description (alt text) for the video */
  description?: string;
  /** embed media flags combined as a bitfield */
  flags?: number;
}

/**
 * Embed Image Structure
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-image-structure
 */
export interface RawEmbedImage {
  /** source url of image (only supports http(s) and attachments) */
  url: string;
  /** a proxied url of the image */
  proxy_url?: string;
  /** height of image */
  height?: number;
  /** width of image */
  width?: number;
  /** the image's media type */
  content_type?: string;
  /** thumbhash placeholder of the image */
  placeholder?: string;
  /** version of the placeholder */
  placeholder_version?: number;
  /** description (alt text) for the image */
  description?: string;
  /** embed media flags combined as a bitfield */
  flags?: number;
}

/**
 * Embed Media Flags
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-media-flags
 */
export const EmbedMediaFlags = {
  /** this image is animated */
  IsAnimated: 1 << 5,
} as const;
export type EmbedMediaFlags =
  (typeof EmbedMediaFlags)[keyof typeof EmbedMediaFlags];

/**
 * Embed Provider Structure
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-provider-structure
 */
export interface RawEmbedProvider {
  /** name of provider */
  name?: string;
  /** url of provider */
  url?: string;
}

/**
 * Embed Author Structure
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-author-structure
 */
export interface RawEmbedAuthor {
  /** name of author */
  name: string;
  /** url of author (only supports http(s)) */
  url?: string;
  /** url of author icon (only supports http(s) and attachments) */
  icon_url?: string;
  /** a proxied url of author icon */
  proxy_icon_url?: string;
}

/**
 * Embed Footer Structure
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-footer-structure
 */
export interface RawEmbedFooter {
  /** footer text */
  text: string;
  /** url of footer icon (only supports http(s) and attachments) */
  icon_url?: string;
  /** a proxied url of footer icon */
  proxy_icon_url?: string;
}

/**
 * Embed Field Structure
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-field-structure
 */
export interface RawEmbedField {
  /** name of the field */
  name: string;
  /** value of the field */
  value: string;
  /** whether or not this field should display inline */
  inline?: boolean;
}

/**
 * Attachment Structure
 * @see https://docs.discord.com/developers/resources/message#attachment-object-attachment-structure
 */
export interface RawAttachment {
  /** attachment id */
  id: Snowflake;
  /** name of file attached */
  filename: string;
  /** the title of the file */
  title?: string;
  /** description (alt text) for the file (max 1024 characters) */
  description?: string;
  /** the attachment's media type */
  content_type?: string;
  /** size of file in bytes */
  size: number;
  /** source url of file */
  url: string;
  /** a proxied url of file */
  proxy_url: string;
  /** height of file (if image or video) */
  height?: number | null;
  /** width of file (if image or video) */
  width?: number | null;
  /** thumbhash placeholder (if image or video) */
  placeholder?: string;
  /** version of the placeholder (if image or video) */
  placeholder_version?: number;
  /** whether this attachment is ephemeral */
  ephemeral?: boolean;
  /** the duration of the audio or video file */
  duration_secs?: number;
  /** base64 encoded bytearray representing a sampled waveform (currently for voice messages) */
  waveform?: string;
  /** attachment flags combined as a bitfield */
  flags?: number;
  /** for Clips, array of users who were in the stream */
  clip_participants?: RawUser[];
  /** for Clips, when the clip was created */
  clip_created_at?: ISO8601Timestamp;
  /** for Clips, the application in the stream, if recognized */
  application?: Partial<RawApplication> | null;
}

/**
 * Attachment Request Structure
 * @see https://docs.discord.com/developers/resources/message#attachment-object-attachment-request-structure
 */
export interface RawAttachmentRequest {
  /** attachment id, for new attachments this must match the `n` in `files[n]` */
  id: Snowflake | number;
  /** name of file attached */
  filename?: string;
  /** the title of the file */
  title?: string;
  /** description (alt text) for the file (max 1024 characters) */
  description?: string;
  /** the duration of the audio or video file (required for voice messages) */
  duration_secs?: number;
  /** base64 encoded bytearray representing a sampled waveform (required for voice messages) */
  waveform?: string;
  /** whether the attachment should be marked as a spoiler and blurred until clicked, this sets the `IS_SPOILER` attachment flag */
  is_spoiler?: boolean;
}

/**
 * Attachment Flags
 * @see https://docs.discord.com/developers/resources/message#attachment-object-attachment-flags
 */
export const AttachmentFlags = {
  /** this attachment is a Clip from a stream */
  IsClip: 1 << 0,
  /** this attachment is the thumbnail of a thread in a media channel, displayed in the grid but not on the message */
  IsThumbnail: 1 << 1,
  /** this attachment has been edited using the remix feature on mobile (deprecated) */
  IsRemix: 1 << 2,
  /** this attachment was marked as a spoiler and is blurred until clicked */
  IsSpoiler: 1 << 3,
  /** this attachment is an animated image */
  IsAnimated: 1 << 5,
} as const;
export type AttachmentFlags =
  (typeof AttachmentFlags)[keyof typeof AttachmentFlags];

/**
 * Channel Mention Structure
 * @see https://docs.discord.com/developers/resources/message#channel-mention-object-channel-mention-structure
 */
export interface RawChannelMention {
  /** id of the channel */
  id: Snowflake;
  /** id of the guild containing the channel */
  guild_id: Snowflake;
  /** the type of channel */
  type: ChannelType;
  /** the name of the channel */
  name: string;
}

/**
 * Allowed Mention Types
 * @see https://docs.discord.com/developers/resources/message#allowed-mentions-object-allowed-mention-types
 */
export const AllowedMentionType = {
  /** Controls role mentions */
  Roles: 'roles',
  /** Controls user mentions */
  Users: 'users',
  /** Controls @everyone and @here mentions */
  Everyone: 'everyone',
} as const;
export type AllowedMentionType =
  (typeof AllowedMentionType)[keyof typeof AllowedMentionType];

/**
 * Default Settings for Allowed Mentions
 * @see https://docs.discord.com/developers/resources/message#allowed-mentions-object-default-settings-for-allowed-mentions
 */
export interface RawAllowedMentions {
  /** An array of allowed mention types to parse from the content */
  parse?: AllowedMentionType[];
  /** Array of role ids to mention, max 100 */
  roles?: Snowflake[];
  /** Array of user ids to mention, max 100 */
  users?: Snowflake[];
  /** For replies, whether to mention the author of the message being replied to, defaults to false */
  replied_user?: boolean;
}

/**
 * Role Subscription Data Object Structure
 * @see https://docs.discord.com/developers/resources/message#role-subscription-data-object-role-subscription-data-object-structure
 */
export interface RawRoleSubscriptionData {
  /** the id of the sku and listing that the user is subscribed to */
  role_subscription_listing_id: Snowflake;
  /** the name of the tier that the user is subscribed to */
  tier_name: string;
  /** the cumulative number of months that the user has been subscribed for */
  total_months_subscribed: number;
  /** whether this notification is for a renewal rather than a new purchase */
  is_renewal: boolean;
}

/**
 * Message Pin Object Structure
 * @see https://docs.discord.com/developers/resources/message#message-pin-object-message-pin-object-structure
 */
export interface RawMessagePin {
  /** the time the message was pinned */
  pinned_at: ISO8601Timestamp;
  /** the pinned message */
  message: RawMessage;
}

/**
 * Shared Client Theme Object Structure
 * @see https://docs.discord.com/developers/resources/message#shared-client-theme-object-shared-client-theme-object-structure
 */
export interface RawSharedClientTheme {
  /** the hexadecimal-encoded colors of the theme (max of 5) */
  colors: string[];
  /** the direction of the theme's colors (max of 360) */
  gradient_angle: number;
  /** the intensity of the theme's colors (max of 100) */
  base_mix: number;
  /** the mode of the theme */
  base_theme?: SharedClientThemeBaseType | null;
}

/**
 * Base Theme Types
 * @see https://docs.discord.com/developers/resources/message#base-theme-types
 */
export const SharedClientThemeBaseType = {
  Unset: 0,
  Dark: 1,
  Light: 2,
  Darker: 3,
  Midnight: 4,
} as const;
export type SharedClientThemeBaseType =
  (typeof SharedClientThemeBaseType)[keyof typeof SharedClientThemeBaseType];

/**
 * Query String Params
 * @see https://docs.discord.com/developers/resources/message#get-channel-messages-query-string-params
 */
export interface GetChannelMessagesQuery {
  /** Get messages around this message ID */
  around?: Snowflake;
  /** Get messages before this message ID */
  before?: Snowflake;
  /** Get messages after this message ID */
  after?: Snowflake;
  /** Max number of messages to return (1-100) */
  limit?: number;
}

/**
 * Query String Params
 * @see https://docs.discord.com/developers/resources/message#search-guild-messages-query-string-params
 */
export interface SearchGuildMessagesQuery {
  /** Max number of messages to return (1-25, default 25) */
  limit?: number;
  /** Number to offset the returned messages by (max 9975) */
  offset?: number;
  /** Get messages before this message ID */
  max_id?: Snowflake;
  /** Get messages after this message ID */
  min_id?: Snowflake;
  /** Max number of words to skip between matching tokens in the search `content` (max 100, default 2) */
  slop?: number;
  /** Filter messages by content (max 1024 characters) */
  content?: string;
  /** Filter messages by these channels (max 500) */
  channel_id?: Snowflake[];
  /** Filter messages by author type */
  author_type?: string[];
  /** Filter messages by these authors (max 100) */
  author_id?: Snowflake[];
  /** Filter messages that mention these users (max 100) */
  mentions?: Snowflake[];
  /** Filter messages that mention these roles (max 100) */
  mentions_role_id?: Snowflake[];
  /** Filter messages that do or do not mention @everyone */
  mention_everyone?: boolean;
  /** Filter messages that reply to these users (max 100) */
  replied_to_user_id?: Snowflake[];
  /** Filter messages that reply to these messages (max 100) */
  replied_to_message_id?: Snowflake[];
  /** Filter messages by whether they are or are not pinned */
  pinned?: boolean;
  /** Filter messages by whether or not they have specific things */
  has?: string[];
  /** Filter messages by embed type */
  embed_type?: string[];
  /** Filter messages by embed provider (case-sensitive, e.g. `Tenor`) (max 256 characters, max 100) */
  embed_provider?: string[];
  /** Filter messages by link hostname (e.g. `discordapp.com`) (max 256 characters, max 100) */
  link_hostname?: string[];
  /** Filter messages by attachment filename (max 1024 characters, max 100) */
  attachment_filename?: string[];
  /** Filter messages by attachment extension (e.g. `txt`) (max 256 characters, max 100) */
  attachment_extension?: string[];
  /** The sorting algorithm to use */
  sort_by?: string;
  /** The direction to sort (`asc` or `desc`, default `desc`) */
  sort_order?: 'asc' | 'desc';
  /** Whether to include results from age-restricted channels (default false) */
  include_nsfw?: boolean;
}

/**
 * Response Body
 * @see https://docs.discord.com/developers/resources/message#search-guild-messages-response-body
 */
export interface SearchGuildMessagesResponse {
  /** Whether the guild is undergoing a deep historical indexing operation */
  doing_deep_historical_index: boolean;
  /** The number of documents that have been indexed during the current index operation, if any */
  documents_indexed?: number;
  /** The total number of results that match the query */
  total_results: number;
  /** A nested array of messages that match the query */
  messages: RawMessage[][];
  /** The threads that contain the returned messages */
  threads?: RawChannel[];
  /** A thread member object for each returned thread the current user has joined */
  members?: RawThreadMember[];
}

/**
 * JSON/Form Params
 * @see https://docs.discord.com/developers/resources/message#create-message-json/form-params
 */
export interface CreateMessageJSONParams {
  /** Message contents (up to 2000 characters) */
  content?: string;
  /** Can be used to verify a message was sent (up to 25 characters). Value will appear in the Message Create event. */
  nonce?: number | string;
  /** `true` if this is a TTS message */
  tts?: boolean;
  /** Up to 10 `rich` embeds (up to 6000 characters) */
  embeds?: RawEmbed[];
  /** Allowed mentions for the message */
  allowed_mentions?: RawAllowedMentions;
  /** Include to make your message a reply or a forward */
  message_reference?: RawMessageReference;
  /** Components to include with the message */
  components?: RawComponent[];
  /** IDs of up to 3 stickers in the server to send in the message */
  sticker_ids?: Snowflake[];
  /** JSON-encoded body of non-file params, only for `multipart/form-data` requests. See Uploading Files */
  payload_json?: string;
  /** Metadata for the attachments. See Uploading Files */
  attachments?: Partial<RawAttachmentRequest>[];
  /** Message flags combined as a bitfield (only `SUPPRESS_EMBEDS`, `SUPPRESS_NOTIFICATIONS`, `IS_VOICE_MESSAGE`, and `IS_COMPONENTS_V2` can be set) */
  flags?: number;
  /** If true and nonce is present, it will be checked for uniqueness in the past few minutes. If another message was created by the same author with the same nonce, that message will be returned and no new message will be created. */
  enforce_nonce?: boolean;
  /** A poll! */
  poll?: RawPollCreateRequest;
  /** The custom client-side theme to share via the message */
  shared_client_theme?: RawSharedClientTheme;
}

/**
 * Query String Params
 * @see https://docs.discord.com/developers/resources/message#get-reactions-query-string-params
 */
export interface GetReactionsQuery {
  /** The type of reaction */
  type?: ReactionType;
  /** Get users after this user ID */
  after?: Snowflake;
  /** Max number of users to return (1-100) */
  limit?: number;
}

/**
 * Reaction Types
 * @see https://docs.discord.com/developers/resources/message#get-reactions-reaction-types
 */
export const ReactionType = {
  Normal: 0,
  Burst: 1,
} as const;
export type ReactionType = (typeof ReactionType)[keyof typeof ReactionType];

/**
 * JSON/Form Params
 * @see https://docs.discord.com/developers/resources/message#edit-message-json/form-params
 */
export interface EditMessageJSONParams {
  /** Message contents (up to 2000 characters) */
  content?: string;
  /** Up to 10 `rich` embeds (up to 6000 characters) */
  embeds?: RawEmbed[];
  /** Edit the flags of a message (`SUPPRESS_EMBEDS` and `IS_COMPONENTS_V2` only) */
  flags?: number;
  /** Allowed mentions for the message */
  allowed_mentions?: RawAllowedMentions;
  /** Components to include with the message */
  components?: RawComponent[];
  /** JSON-encoded body of non-file params (multipart/form-data only). See Uploading Files */
  payload_json?: string;
  /** Attached files to keep and their metadata. See Uploading Files */
  attachments?: Partial<RawAttachmentRequest>[];
}

/**
 * JSON Params
 * @see https://docs.discord.com/developers/resources/message#bulk-delete-messages-json-params
 */
export interface BulkDeleteMessagesJSONParams {
  /** an array of message ids to delete (2-100) */
  messages: Snowflake[];
}

/**
 * Query String Params
 * @see https://docs.discord.com/developers/resources/message#get-channel-pins-query-string-params
 */
export interface GetChannelPinsQuery {
  /** Get messages pinned before this timestamp */
  before?: ISO8601Timestamp;
  /** Max number of pins to return (1-50) */
  limit?: number;
}

/**
 * Response Structure
 * @see https://docs.discord.com/developers/resources/message#get-channel-pins-response-structure
 */
export interface GetChannelPinsResponse {
  items: RawMessagePin[];
  has_more: boolean;
}

/**
 * Embed Types
 * @see https://docs.discord.com/developers/resources/message#embed-object-embed-types
 */
export type EmbedType =
  'rich' | 'image' | 'video' | 'gifv' | 'article' | 'link' | 'poll_result';

/**
 * Message Interaction Metadata: its shape depends on the interaction type.
 * @see https://docs.discord.com/developers/resources/message#message-interaction-metadata-object
 */
export type RawMessageInteractionMetadata =
  | RawApplicationCommandInteractionMetadata
  | RawMessageComponentInteractionMetadata
  | RawModalSubmitInteractionMetadata;
